name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
   
    - name: Checkout
      uses: actions/checkout@v1

    - name: Run gitbook
      run: |
        # https://github.com/GitbookIO/gitbook/blob/master/docs/setup.md
        npm install gitbook-cli
        node ./node_modules/gitbook-cli/bin/gitbook.js build . public --log=debug --debug

    - name: GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v1.2.5
      with:
        target_branch: gh-pages
        build_dir: public
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
